# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8748fc0d7d6489ef843af9bf3b8683fba9ccf1e020a137d386b1b7a140c718c4d9861e36969fb65f4d03c52347b12b4742a23c4e65e7fd360e6e422f7e2291

test:
  secret_key_base: 673e603b7bf8dee657ff65b9f0a261749d6cbb2ce38d60fc111c037e3108a8ea1f3e5dffc9921839bf2997b2eda11efb33e1aebf62b7dea58ca25577d8fadab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
